Document: openca-tools
Title: Debian openca-tools Manual
Author: <insert document author here>
Abstract: This manual describes what openca-tools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openca-tools/openca-tools.sgml.gz

Format: postscript
Files: /usr/share/doc/openca-tools/openca-tools.ps.gz

Format: text
Files: /usr/share/doc/openca-tools/openca-tools.text.gz

Format: HTML
Index: /usr/share/doc/openca-tools/html/index.html
Files: /usr/share/doc/openca-tools/html/*.html
